readme modified and diagram added
devopsacademyau/2020-feb-project1-group3 pull request #15
Opened 2020-04-07 09:58 UTC by andreazzabr

2020-04-08 03:16 UTC, hsy3418 reviewed
I am thinking for the final infrastructure diagram, might need to add more details: IGW,NGW, route tables and security group details.

2020-04-15 04:36 UTC, hsy3418 commented
I had done a bit of poc on storage and also discussed with Caio, instead of S3, using EFS will be a better solutions for Wordpress storage, it is easy to be mounted in ECS, do you want to change your diagram?

2020-04-15 22:28 UTC, caiocezart requested changes
EFS is also within the vpc on the subnets

Also, could you please add some documentation?

2020-04-16 14:06 UTC, andreazzabr commented
new diagram added
readme.md updated

2020-04-16 23:08 UTC, caiocezart requested changes

2020-04-16 23:08 UTC, caiocezart commented on README.md
> +[PR1-grp3](images/PR1-grp3.png)
attach the image to the documentation so you don't need to click to see it

`![<some-alt-text>](images/PR1-grp3.png)`

2020-04-16 23:08 UTC, caiocezart commented on README.md
> +[PR1-grp3](images/PR1-grp3.png)
and please give me a few words for each one of the elements of the diagram

2020-04-18 09:21 UTC, caiocezart commented
this fix #3

2020-04-27 08:23 UTC, caiocezart approved these changes

2020-04-27 08:25 UTC, merged