Feature/script
devopsacademyau/2020-feb-project1-group3 pull request #32
Opened 2020-04-26 12:49 UTC by hsy3418

- refactor the code by creating modules
- create makefile

2020-04-26 20:45 UTC, caiocezart requested changes
nice work @hsy3418 👏 just small notes already mentioned before

wait for others to finish the last modules, update your code and fix merge conflicts as you are changing their files

2020-04-26 20:45 UTC, caiocezart commented on docker-compose.yml
> +      - ~/.aws:/home/terraform/.aws
fix permissions volume

2020-04-26 20:45 UTC, caiocezart commented on terraform/ecs/ecs.tf
> +  name = "ecsTaskExecutionRole"
as explained in slack, we need this as a separate role.. @CarineOliveira will fix on her code

2020-04-27 08:23 UTC, caiocezart submitted a review, later dismissed

2020-04-28 01:23 UTC, CarineOliveira submitted a review, later dismissed

2020-04-28 01:28 UTC, CarineOliveira approved these changes

2020-04-28 01:30 UTC, merged